BEGIN;
--
-- Create model Admin
--
CREATE TABLE "index_admin" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "login" varchar(80) NOT NULL, "password" varchar(80) NOT NULL);
--
-- Create model Categories
--
CREATE TABLE "index_categories" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category_name" varchar(90) NOT NULL, "approved" boolean NOT NULL, "category_of_id_id" bigint NULL);
--
-- Create model Crop
--
CREATE TABLE "index_crop" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "crop_name" varchar(80) NOT NULL, "description" varchar(80) NOT NULL, "price" numeric(8, 2) NOT NULL, "amount" integer NOT NULL CHECK ("amount" >= 0), "origin" varchar(80) NOT NULL, "crop_year" date NULL, "price_type" varchar(5) NOT NULL, "category_id" bigint NOT NULL);
--
-- Create model User
--
CREATE TABLE "index_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_name" varchar(80) NOT NULL, "email" varchar(80) NOT NULL, "password" varchar(80) NOT NULL, "mod" boolean NOT NULL);
--
-- Create model Review
--
CREATE TABLE "index_review" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "short_desc" varchar(80) NOT NULL, "long_desc" varchar(200) NOT NULL, "stars" integer NOT NULL CHECK ("stars" >= 0), "crop_id" bigint NOT NULL, "reviewed_by_id" bigint NOT NULL);
--
-- Create model Order
--
CREATE TABLE "index_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "total_price" double precision NOT NULL, "amount" integer NOT NULL CHECK ("amount" >= 0), "state" varchar(10) NOT NULL, "crop_id" bigint NOT NULL, "farmer_id" bigint NOT NULL, "ordered_by_id" bigint NOT NULL);
--
-- Create model Harvest
--
CREATE TABLE "index_harvest" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "place" varchar(80) NOT NULL, "description" varchar(80) NOT NULL, "max_occupancy" integer NOT NULL CHECK ("max_occupancy" >= 0), "current_occupancy" integer NOT NULL CHECK ("current_occupancy" >= 0), "crop_id" bigint NOT NULL, "farmer_id" bigint NOT NULL);
CREATE TABLE "index_harvest_attendees" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "harvest_id" bigint NOT NULL, "user_id" bigint NOT NULL);
--
-- Add field farmer to crop
--
ALTER TABLE "index_crop" ADD COLUMN "farmer_id" bigint NOT NULL CONSTRAINT "index_crop_farmer_id_40ffd9d8_fk_index_user_id" REFERENCES "index_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "index_crop_farmer_id_40ffd9d8_fk_index_user_id" IMMEDIATE;
ALTER TABLE "index_categories" ADD CONSTRAINT "index_categories_category_of_id_id_a10a3d03_fk_index_cat" FOREIGN KEY ("category_of_id_id") REFERENCES "index_categories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_categories_category_of_id_id_a10a3d03" ON "index_categories" ("category_of_id_id");
ALTER TABLE "index_crop" ADD CONSTRAINT "index_crop_category_id_36e5decb_fk_index_categories_id" FOREIGN KEY ("category_id") REFERENCES "index_categories" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_crop_category_id_36e5decb" ON "index_crop" ("category_id");
ALTER TABLE "index_review" ADD CONSTRAINT "index_review_crop_id_5618de0d_fk_index_crop_id" FOREIGN KEY ("crop_id") REFERENCES "index_crop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "index_review" ADD CONSTRAINT "index_review_reviewed_by_id_bda58038_fk_index_user_id" FOREIGN KEY ("reviewed_by_id") REFERENCES "index_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_review_crop_id_5618de0d" ON "index_review" ("crop_id");
CREATE INDEX "index_review_reviewed_by_id_bda58038" ON "index_review" ("reviewed_by_id");
ALTER TABLE "index_order" ADD CONSTRAINT "index_order_crop_id_7ad16a04_fk_index_crop_id" FOREIGN KEY ("crop_id") REFERENCES "index_crop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "index_order" ADD CONSTRAINT "index_order_farmer_id_86f99168_fk_index_user_id" FOREIGN KEY ("farmer_id") REFERENCES "index_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "index_order" ADD CONSTRAINT "index_order_ordered_by_id_8f50a69e_fk_index_user_id" FOREIGN KEY ("ordered_by_id") REFERENCES "index_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_order_crop_id_7ad16a04" ON "index_order" ("crop_id");
CREATE INDEX "index_order_farmer_id_86f99168" ON "index_order" ("farmer_id");
CREATE INDEX "index_order_ordered_by_id_8f50a69e" ON "index_order" ("ordered_by_id");
ALTER TABLE "index_harvest" ADD CONSTRAINT "index_harvest_crop_id_bb87f489_fk_index_crop_id" FOREIGN KEY ("crop_id") REFERENCES "index_crop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "index_harvest" ADD CONSTRAINT "index_harvest_farmer_id_d30cda67_fk_index_user_id" FOREIGN KEY ("farmer_id") REFERENCES "index_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_harvest_crop_id_bb87f489" ON "index_harvest" ("crop_id");
CREATE INDEX "index_harvest_farmer_id_d30cda67" ON "index_harvest" ("farmer_id");
ALTER TABLE "index_harvest_attendees" ADD CONSTRAINT "index_harvest_attendees_harvest_id_user_id_d9d16ddc_uniq" UNIQUE ("harvest_id", "user_id");
ALTER TABLE "index_harvest_attendees" ADD CONSTRAINT "index_harvest_attendees_harvest_id_51cab504_fk_index_harvest_id" FOREIGN KEY ("harvest_id") REFERENCES "index_harvest" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "index_harvest_attendees" ADD CONSTRAINT "index_harvest_attendees_user_id_d0fc7ccf_fk_index_user_id" FOREIGN KEY ("user_id") REFERENCES "index_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "index_harvest_attendees_harvest_id_51cab504" ON "index_harvest_attendees" ("harvest_id");
CREATE INDEX "index_harvest_attendees_user_id_d0fc7ccf" ON "index_harvest_attendees" ("user_id");
CREATE INDEX "index_crop_farmer_id_40ffd9d8" ON "index_crop" ("farmer_id");
COMMIT;
