# Generated by Django 4.1.2 on 2022-11-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_farmer', to='index.user'),
        ),
    ]
