# Generated by Django 4.0.5 on 2022-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mod',
            field=models.BooleanField(default=False),
        ),
    ]
