# Generated by Django 4.1.2 on 2022-11-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_of_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.categories'),
        ),
    ]
