# Generated by Django 4.1.2 on 2022-11-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_crop_amount_alter_crop_crop_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
