# Generated by Django 4.1.2 on 2022-11-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_crop_crop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_year',
            field=models.DateField(null=True),
        ),
    ]
