# Generated by Django 4.0.5 on 2022-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='pieces',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='weight',
        ),
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
