# Generated by Django 4.0.5 on 2022-11-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_pieces_crop_amount_remove_crop_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
