# Generated by Django 4.0.5 on 2022-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_categories_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pen', 'pending'), ('rej', 'rejected'), ('con', 'confirmed')], default='pending', max_length=10),
        ),
    ]
